outputFormats:
  manifest:
    name: manifest
    baseName: manifest
    mediaType: application/json
    notAlternative: false
  cmsconfig:
    name: cmsconfig
    baseName: cmsconfig
    mediaType: application/yaml
    notAlternative: false
markup:
  goldmark:
    extensions:
      definitionList: true
      footnote: true
taxonomy:
  authors: author