outputFormats:
  manifest:
    name: manifest
    baseName: manifest
    mediaType: application/json
    notAlternative: false
markup:
  goldmark:
    extensions:
      definitionList: true
      footnote: true